default_pulling_interval: 10
token: "NGOrDGRHzuDjVZ5xSzCD5wUpiFHQ8AKzhKSqDK90"
platform_host_url: http://localhost:8080
chunk_size: 1000
plugins:
  - type: mysql
    name: mysql_adapter
    description: "" # Optional string
    database: sakila
    host: localhost
    port: 3306
    user: root
    ssl_disabled: False # Optional, default: False